name: autocomplete

services:
  backend:
    build: ./backend
    
    ports:
      - 4000:4000

  frontend:
    build: ./frontend

    depends_on:
      - backend

    environment:
      - WDS_SOCKET_HOST=127.0.0.1 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 

    ports:
      - 3000:3000